apiVersion: v1
kind: Secret

metadata:
  name: grocery-secret
  namespace: grocery

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: "YOUR_ROOT_PASSWORD_HERE"
  MYSQL_DATABASE: "grocery"
  MYSQL_USER: "YOUR_DB_USER_HERE"
  MYSQL_PASSWORD: "YOUR_DB_PASSWORD_HERE"
